add more dinosaurs!

diff --git a/dl b/dl
--- a/dl
+++ b/dl
@@ -1,10 +1,20 @@
 #!/bin/bash
 
+set -e
+
 line="$1"
 path="`echo "$line" | cut -d' ' -f 1`"
 url="`echo "$line" | cut -d' ' -f 2`"
 
-curl "$url" --create-dirs -o "./models/$path"
-[ $? != 0 ] && echo "$path" >> error
+out_path=models/"$path"
 
-echo "$path --- $url"
+if [ -f "$out_path" ]; then
+    exit 0
+fi
+
+valid_glb=1
+curl "$url" --create-dirs -o "$out_path" || valid_glb=0
+file "$out_path" | grep 'glTF binary model' || valid_glb=0
+[ $valid_glb -eq 0 ] && echo "$path" >> errors && rm -f "$out_path" 
+
+echo "$url"
